### ISSUE TITLE
When testing with the retrained model, I encountered this error. May I ask why?

### ISSUE THREAD

**Issue by song6174** [TencentARC/Mix-of-Show#18]
I have configured the test.yml like this:
```
name: 1001_EDLoRA_hina_Anyv4_B4_Iter1K
manual_seed: 0
mixed_precision: fp16

# dataset and data loader settings
datasets:
  val_vis:
    name: PromptDataset
    prompts: datasets/validation_prompts/single-concept/characters/test_girl.txt
    num_samples_per_prompt: 8
    latent_size: [ 4,64,64 ]
    replace_mapping:
      <TOK>: <hina1> <hina2>
    batch_size_per_gpu: 4

models:
  pretrained_path: experiments/pretrained_models/anything-v4.0
  enable_edlora: true  # true means ED-LoRA, false means vallina LoRA
  alpha_list: [0, 0.4, 0.6, 1.0] # 0 means only visualize embedding (without lora weight)

# path
path:
  lora_path: temp/Application_Branch/single_concept_model/1001_1_EDLoRA_hina_Anyv4_B4_Repeat500/models/edlora_model-latest.pth

# validation settings
val:
  compose_visualize: true
  alpha_list: [0, 0.7, 1.0] # 0 means only visualize embedding (without lora weight)
  sample:
    num_inference_steps: 50
    guidance_scale: 7.5
```

And I received the following error while running test_edlora.py.
```
ValueError: EDLoRAPipeline {                                                                                                                                                                                                                  
  "_class_name": "EDLoRAPipeline",                                                                                     
  "_diffusers_version": "0.24.0",                                                                                                                                                                                                             
  "_name_or_path": "experiments/pretrained_models/anything-v4.0",
  "scheduler": [                                                                                                                                                                                                                              
    "diffusers",                                                                                                                                                                                                                              
    "DPMSolverMultistepScheduler"                                                                                                                                                                                                             
  ],                                          
  "text_encoder": [
    "transformers",
    "CLIPTextModel"
  ],
  "tokenizer": [
    "transformers",
    "CLIPTokenizer"
  ],
  "unet": [
    "diffusers",
    "UNet2DConditionModel"
  ],
  "vae": [
    "diffusers",
    "AutoencoderKL"
  ]
}
 has been incorrectly initialized or <class 'mixofshow.pipelines.pipeline_edlora.EDLoRAPipeline'> is incorrectly implemented. Expected {'vae', 'text_encoder', 'unet', 'tokenizer', 'safety_checker', 'scheduler', 'feature_extractor'} to be defined, but dict_keys(['vae', 'text_encoder', 'tokenizer', 'unet', 'scheduler']) are defined.
```

I am also curious about what configure I should pass in for the alpha_list?
